FROM postgres:15

RUN apt-get update && apt-get -y install git build-essential postgresql-server-dev-15

RUN git clone https://github.com/citusdata/pg_cron.git
RUN cd pg_cron && make && make install
RUN chown postgres /var/lib/postgresql/data/
COPY ./init-db /docker-entrypoint-initdb.d