-- Date: 2023-01-25

CREATE SEQUENCE IF NOT EXISTS client_seq MINVALUE 1 START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS friend_seq MINVALUE 1 START WITH 1 INCREMENT BY 1;

ALTER TABLE friend ADD COLUMN rejected boolean NOT NULL DEFAULT FALSE;

