-- Date: 2023-02-04

CREATE SEQUENCE IF NOT EXISTS business_seq MINVALUE 0 START WITH 0 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS branch_seq MINVALUE 0 START WITH 0 INCREMENT BY 1;

ALTER TABLE branch 
    ALTER COLUMN score SET DATA TYPE FLOAT;