-- Date: 2023-02-05

ALTER TABLE reservation ADD status INT NOT NULL;
ALTER TABLE reservation ADD pay_date TIMESTAMP NOT NULL;
ALTER TABLE reservation ADD price INT NOT NULL;

CREATE SEQUENCE IF NOT EXISTS reservation_seq MINVALUE 0 START WITH 0 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS client_group_seq MINVALUE 0 START WITH 0 INCREMENT BY 1;