name: Dev Pull Request

on:
  pull_request:
    branches:
      - develop

env:
  JAVA_VERSION: 1.17
jobs:
  build:
    name: Build Image
    runs-on: [self-hosted, dev.paca]
    outputs:
      BUILD_NUMBER: ${{steps.build-number.outputs.BUILD_NUMBER}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEM }}

      - name: Build Number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%-d.%-m.%Y.%-H.%-M.%-S')" >> $GITHUB_OUTPUT

      - name: Run maven package script
        id: maven-build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dev.paca-api:${{steps.build-number.outputs.BUILD_NUMBER}} -t ${{ secrets.DOCKERHUB_USERNAME }}/dev.paca-api:latest .